let {url, method, headers, body} = $request;

if (body.indexOf('EN9DBC0BEFD572CC5478077220FA40BFAD') > 0) {

    let html = $response.body;

    html = html = JSON.stringify({
        "errMsg": "",
        "data": {
            "SKIP_URL": "",
            "MSPS_ENTITY": {
                "Coupon_DISCRIPTION": "1.建行生活平台用户可在2023年12月28日15:00:00在平台首页“数币来助力，姑苏更优惠”活动页面领取1张满200元减100元数字人民币红包凭证，活动期间共计8000份。<br>2.红包凭证仅作为相同面额数字人民币红包领取凭证，不可核销，红包凭证对应的数字人民币红包面额与凭证相同，数字人民币红包将于2023年12月29日24点前到达建行生活注册手机号对应的建行一二类数字人民币钱包中（如遇数字人民币钱包未开立或钱包状态异常则无法到账）<br>3.红包凭证对应的数字人民币红包面额为满200元减100元，红包有效期7天，逾期未使用则予以回收，且不能参与后续滚动发放领取。<br>4.红包凭证对应的数字人民币红包可用商户详见活动页面右侧数币红包可用门店。",
                "Mdl_Val_ValSt": "10",
                "LIMIT_MIN_PAY": "200.00",
                "Avy_Plc_Dsc": "苏州",
                "Dslmr_Sttmnt_Inf": "1.活动过程中，如用户出现或涉嫌参与违法违规行为(包括但不限于，恶意获取活动参与或购券资格、利用不正当手段盗刷平台奖品及代金券等)，中国建设银行有权撤销用户的活动参与资格、优惠券使用资格，并有权撤销违规交易，回收用户已经获得的奖励权益（包含已消费部分），必要时将追究用户法律责任。<br>2.在法律许可范围内，中国建设银行有权修订本活动条款及细则(包括但不限于参加资格、奖励方式等)、暂停或取消本活动，并经相关途径(如建行网站、手机银行、微信公众号、建行生活等 )公告后生效。购买本优惠券的用户即视为了解并同意遵守规则。<br>3.用户需使用最新版本【建行生活APP】手机客户端参与本活动。因用户电子设备不支持、APP未更新到最新版本、卡片挂失或换卡等自身原因，或其他系统问题导致无法享受活动优惠的，中国建设银行不承担责任。",
                "DcCp_Avy_Dtls_CntDsc": "",
                "EFFECT_DELAY_WEEK": "",
                "STOCK": "8000",
                "Coupon_ICON": "http://img.longpay.ccb.com/cosimg/heroes/api/v1/image/20231215/PIC2312151656460117937463.png",
                "EFFECT_COUPON_DEADLINE": "20240104235959",
                "Coupon_Mrch_List": {
                    "Coupon_Mrch_Name": "吴江区黎里镇宏乐纺织品经营部",
                    "Coupon_Mrch_ID": "999930000355884",
                    "Coupon_Mrch_Addr": "黎里镇新阳路88号",
                    "DAY_MCHA_AMOUNT_LIMIT": "1.00",
                    "Rltv_Prim_Asst_Itm_ID": "105000159493844",
                    "Coupon_Mrch_Tel": "13913080200",
                    "MCHA_AMOUNT_LIMIT": "1.00",
                    "USED_MONEY": "0.00",
                    "Lgt": "120.79341034651",
                    "DAY_USED_MONEY": "0.00",
                    "distance": "",
                    "Ltt": "30.99427069408"
                },
                "BookEntr_InsID": "",
                "Tx_Prvn_Dtl_Cntnt": "已开通建行一二类数字人民币钱包（钱包状态正常）的建行生活平台注册用户",
                "DcCp_Shlvs_Tm": "",
                "TYPE_DIS_RATE": "",
                "Coupon_Mrch_Type": "ORGZ",
                "Mrch_ID": "",
                "Exmpt_Fee_Amt_Tp_Ind": "0",
                "USE_MEMBER_lEVEL_LIMIT": "",
                "Act_ID": "",
                "CshRs_Vrf_Mode_Cd": "",
                "CcyCd": "",
                "TYPE_DIS_LIMIT": "",
                "Remain_Num": "10",
                "UsgMd_Dsc": "红包凭证仅作为相同面额数字人民币红包领取凭证，不可核销，用户可在2023年12月29日24点前在数字人民币APP中查看数字人民币红包，红包在指定门店使用数字人民币APP的建设银行钱包支付满减抵扣。",
                "Coupon_Mrch_Num": "1",
                "USE_GUIDE": "红包凭证仅作为相同面额数字人民币红包领取凭证，不可核销，用户可在2023年12月29日24点前在数字人民币APP中查看数字人民币红包，红包在指定门店使用数字人民币APP的建设银行钱包支付满减抵扣，红包可用商户详见活动页面右侧活动规则。",
                "Oprt_MtIt_ID": "",
                "RetGds_TpCd": "",
                "EFFECT_DELAY_DAY": "",
                "TYPE_QT_AMOUNT": "100.00",
                "Ovd_RfVh_Ind": "",
                "Scn_TpCd": "00",
                "EFFECT_DELAY_DAY_COUNT": "7",
                "EFFECT_DELAY_MONTH": "",
                "Bmp_ECD": "WL02",
                "Hold_Pct": "",
                "ASPD_ECD": "",
                "EFFECT_PERIOD_START": "20231228150000",
                "Scn_Rght_TpCd": "00",
                "Avy_Tm_Dsc": "2023年12月28日",
                "IvsEntRcrdRegDptNm": "",
                "CARD_BIN_NEED": "0",
                "NEED_PHONE": "",
                "disabled": "0",
                "Coupon_ID": "EN9DBC0BEFD572CC5478077220FA40BFAD",
                "Coupon_NAME": "姑苏更优惠满200元减100元数字人民币红包凭证",
                "Need_White_List": "0",
                "Drw_Cnt_Dsc": "每人限领1张",
                "SpBkAtAyTm_Ind": "",
                "PyMd_Dsc": "红包凭证仅作为相同面额数字人民币红包领取凭证，不可核销，用户可在2023年12月29日24点前在数字人民币APP中查看数字人民币红包，红包在指定门店使用数字人民币APP的建设银行钱包支付满减抵扣。",
                "Drw_Tm_Dsc": "2023年12月28日15:00:00——23:59:59",
                "Idx_Show_Ind": "0",
                "PDPrc": "",
                "Rcrd_Ctf_ID": "",
                "CtcPsn_Nm": "",
                "CtcPsn_Move_TelNo": "",
                "personGetLimit": "1",
                "useConditionType": "0",
                "TYPE_ENT_STAFF": "",
                "EFFECT_PERIOD_END": "20231228235959",
                "Has_Receive_Count": "8000",
                "Coupon_IMG": "http://img.longpay.ccb.com/cosimg/heroes/api/v1/image/20231215/PIC2312151656386183704448.png",
                "TYPE": "QUOTA",
                "EFFECT": ""
            },
            "SURPLUS_STOCK": "10",
            "PERSON_GET_LIMIT": "1",
            "IS_SHOW_CODE": "0",
            "USER_GET_NUM": "",
            "SYSTEM_TIME": "2023-12-28 15:19:05",
            "USER_USED_NUM": ""
        },
        "reqFlowNo": "1051003691703747945961000",
        "errCode": "0"
    });
}

$done({body: html});
